databases:
  pets:
    datasource:
      url: "jdbc:h2:mem:pets"
    jpa:
      properties.hibernate.hbm2ddl.auto: create-drop
  plants:
    url: "jdbc:h2:mem:plants"
    jpa:
      properties.hibernate.hbm2ddl.auto: create-drop
